name: RelativeCI

on:
  workflow_run:
    workflows: ['Pull request tests']
    types:
      - completed

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          key: ${{ secrets.RELATIVE_CI_KEY }}
